//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassTransit.Integration.Routing.Configuration
{
    
    
    /// <summary>
    /// The MessageRoutingSettings Configuration Section.
    /// </summary>
    public partial class MessageRoutingSettings : global::System.Configuration.ConfigurationSection
    {
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::MassTransit.Integration.Routing.Configuration.MessageRoutingSettings.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::MassTransit.Integration.Routing.Configuration.MessageRoutingSettings.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Routes Property
        /// <summary>
        /// The XML name of the <see cref="Routes"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string RoutesPropertyName = "routes";
        
        /// <summary>
        /// Gets or sets the Routes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Routes.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::MassTransit.Integration.Routing.Configuration.MessageRoutingSettings.RoutesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::MassTransit.Integration.Routing.Configuration.RouteToCollection Routes
        {
            get
            {
                return ((global::MassTransit.Integration.Routing.Configuration.RouteToCollection)(base[global::MassTransit.Integration.Routing.Configuration.MessageRoutingSettings.RoutesPropertyName]));
            }
            set
            {
                base[global::MassTransit.Integration.Routing.Configuration.MessageRoutingSettings.RoutesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace MassTransit.Integration.Routing.Configuration
{
    
    
    /// <summary>
    /// A collection of MessageTypeCollection instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::MassTransit.Integration.Routing.Configuration.RouteToCollection.MessageTypeCollectionPropertyName)]
    public partial class RouteToCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string MessageTypeCollectionPropertyName = "routeTo";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::MassTransit.Integration.Routing.Configuration.RouteToCollection.MessageTypeCollectionPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::MassTransit.Integration.Routing.Configuration.RouteToCollection.MessageTypeCollectionPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection)(element)).Uri;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection this[int index]
        {
            get
            {
                return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> with the specified key.
        /// </summary>
        /// <param name="uri">The key of the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection this[object uri]
        {
            get
            {
                return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection)(base.BaseGet(uri)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="routeTo">The <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection routeTo)
        {
            base.BaseAdd(routeTo);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="routeTo">The <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection routeTo)
        {
            base.BaseRemove(this.GetElementKey(routeTo));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection GetItemAt(int index)
        {
            return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> with the specified key.
        /// </summary>
        /// <param name="uri">The key of the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection GetItemByKey(string uri)
        {
            return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection)(base.BaseGet(((object)(uri)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace MassTransit.Integration.Routing.Configuration
{
    
    
    /// <summary>
    /// A collection of MessageTypeElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::MassTransit.Integration.Routing.Configuration.MessageTypeElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection.MessageTypeElementPropertyName)]
    public partial class MessageTypeCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string MessageTypeElementPropertyName = "messageType";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override string ElementName
        {
            get
            {
                return global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection.MessageTypeElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection.MessageTypeElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeElement)(element)).Type;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::MassTransit.Integration.Routing.Configuration.MessageTypeElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::MassTransit.Integration.Routing.Configuration.MessageTypeElement this[int index]
        {
            get
            {
                return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> with the specified key.
        /// </summary>
        /// <param name="type">The key of the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::MassTransit.Integration.Routing.Configuration.MessageTypeElement this[object type]
        {
            get
            {
                return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeElement)(base.BaseGet(type)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="messageType">The <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Add(global::MassTransit.Integration.Routing.Configuration.MessageTypeElement messageType)
        {
            base.BaseAdd(messageType);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="messageType">The <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public void Remove(global::MassTransit.Integration.Routing.Configuration.MessageTypeElement messageType)
        {
            base.BaseRemove(this.GetElementKey(messageType));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::MassTransit.Integration.Routing.Configuration.MessageTypeElement GetItemAt(int index)
        {
            return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> with the specified key.
        /// </summary>
        /// <param name="type">The key of the <see cref="global::MassTransit.Integration.Routing.Configuration.MessageTypeElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public global::MassTransit.Integration.Routing.Configuration.MessageTypeElement GetItemByKey(string type)
        {
            return ((global::MassTransit.Integration.Routing.Configuration.MessageTypeElement)(base.BaseGet(((object)(type)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Uri Property
        /// <summary>
        /// The XML name of the <see cref="Uri"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string UriPropertyName = "uri";
        
        /// <summary>
        /// Gets or sets the Uri.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Uri.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection.UriPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Uri
        {
            get
            {
                return ((string)(base[global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection.UriPropertyName]));
            }
            set
            {
                base[global::MassTransit.Integration.Routing.Configuration.MessageTypeCollection.UriPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace MassTransit.Integration.Routing.Configuration
{
    
    
    /// <summary>
    /// The MessageTypeElement Configuration Element.
    /// </summary>
    public partial class MessageTypeElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Type Property
        /// <summary>
        /// The XML name of the <see cref="Type"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        internal const string TypePropertyName = "type";
        
        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.7")]
        [global::System.ComponentModel.DescriptionAttribute("The Type.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::MassTransit.Integration.Routing.Configuration.MessageTypeElement.TypePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Type
        {
            get
            {
                return ((string)(base[global::MassTransit.Integration.Routing.Configuration.MessageTypeElement.TypePropertyName]));
            }
            set
            {
                base[global::MassTransit.Integration.Routing.Configuration.MessageTypeElement.TypePropertyName] = value;
            }
        }
        #endregion
    }
}
